name: recommend_movielens
model:
  name: lightgbm_regression
  params:
    boosting_type: gbdt
    n_estimators: 1000
    objective: rmse
    metric: rmse
    learning_rate: 0.03
    num_leaves: 31
    min_data_in_leaf: 20
    random_state: 42
    importance_type: gain
  train_params:
    early_stopping_rounds: 10
    log_evaluation: 10

period:
  validation:
    user_recency_records: 5
